# Generated by Django 2.2.1 on 2019-05-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=100)),
                ('marketplace', models.CharField(default='', max_length=100)),
                ('orderId', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('lastChange', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
