# Generated by Django 2.2.1 on 2019-05-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='domain',
            new_name='Domain',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastChange',
            new_name='LastChange',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='marketplace',
            new_name='Marketplace',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderId',
            new_name='OrderId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='State',
        ),
    ]
