# Generated by Django 2.2.1 on 2019-05-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190506_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Marketplace',
        ),
    ]
